### ISSUE TITLE
Apply on Mobile 

### ISSUE THREAD

**Issue by talent1** [bullhorn/career-portal#192]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

## Current behavior
Apply Now button doesn't seem to work on mobile. Rather than just clicking the apply button you have to hold it down until it highlights and then double tap - a candidate wouldn't just guess that they'd have to do that. I'm concerned we're losing applications because of the process. Is there a way to make the button work better?
-

## Expected behavior

- Tap on Apply Now and have the application screen immediately pop up.

## Steps to replicate behavior

1.

## Screenshots

__Current__

__Expected__

**Comment by charlesabarnes** [comment]
Hello, 

This issue was fixed via one of the recent versions of the career portal via #133.

I suggest heading over to the [releases](https://github.com/bullhorn/career-portal/releases) page and downloading the most recent version of the career portal.

**Comment by talent1** [comment]
Hi, 

We just downloaded the most recent version, but still have the same problem. Do you have any other suggestions on how to fix this? Thanks.

**Comment by charlesabarnes** [comment]
Can you shoot me a link to your portal so I can take a look?
