### ISSUE TITLE
Bullhorn Career Portal Blank Page on GoDaddy Windows Plesk

### ISSUE THREAD

**Issue by PatriotPlacements** [bullhorn/career-portal#200]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

Bullhorn Career Portal Opens with a blank page on GoDaddy Windows Plesk

-

I downloaded 2.5.1 and the career portal renders fine on my local machine.

-

I used IpSwitch FTP to upload.

1.

## Screenshots

![capture1](https://user-images.githubusercontent.com/39683988/40595859-2a33301c-6205-11e8-9ee7-7d4d9b8086ba.JPG)

In Debugger:
Source map error: request failed with status 404
Resource URL: https://patriotplacements.org/scripts/vendor.js
Source Map URL: angular-tooltips.js.map[Learn More]
Source map error: request failed with status 404
Resource URL: https://patriotplacements.org/styles/vendor.css
Source Map URL: angular-tooltips.css.map[Learn More]

__Expected__
![image](https://user-images.githubusercontent.com/39683988/40595881-4150638c-6205-11e8-9613-fc83b7392ef5.png)

Thank you.

**Comment by charlesabarnes** [comment]
Heya, 
Do you have a public version of the site so I can take a look?  From the details given I am not too sure what is going on just yet.

Thanks

**Comment by PatriotPlacements** [comment]
Hi Charles:


Unfortunately, we don't have a sandbox.  Last night I brought our site down to test this.  What I did do is rename index.html to careerportal.html and put the files on the same root as our website.  You can see it by going to:   http://patriotplacements.org/careerportal.html


I ran the web developer tools in Edge and Firefox from there.


Any help is greatly appreciated!



Thank you,
Carmelita Resh
Founder/CEO
Patriot Placements, Inc.

<http://www.patriotplacements.org/><http://www.patriotplacements.org>www.patriotplacements.org<http://www.patriotplacements.org/>

[1464298387064_PatriotPlacementsLogo]

Feel free to follow us on Facebook, Twitter or LinkedIn via our website at <http://www.patriotplacements.org/> http://www.patriotplacements.org<http://patriotplacements.org/>



________________________________

**Comment by PatriotPlacements** [comment]
Morning! I was having the same problem with the fonts and styles folders during troubleshooting.  I read about this in a post and there may be concerns that it may affect the site. Please confirm what the MIME type should be and where I would set it.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by charlesabarnes** [comment]
Hey @PatriotPlacements That should be fixed with the most current release, however the mime type is `font/woff`

**Comment by charlesabarnes** [comment]
We addressed fonts in v2.6.0.  That should resolve any path issues that result in 404 errors.  The mime type however that you may need is 

`font/woff2`

**Comment by PatriotPlacements** [comment]
Thank you Charles, but with a blank page, there is still an issue with the downloaded code on GoDaddy's Windows Plesk platform that neither I nor GoDaddy could resolve.  It would help if you can tell me a bit of how it was resolved. For example, was it a javascript issue?


Where in the code should the font be declared?  Do you have a line of code on my side or is that something GoDaddy needs to do?


Thank you,
Carmelita Resh
Founder/CEO
Patriot Placements, Inc.

<http://www.patriotplacements.org/><http://www.patriotplacements.org>www.patriotplacements.org<http://www.patriotplacements.org/>

[1464298387064_PatriotPlacementsLogo]

Feel free to follow us on Facebook, Twitter or LinkedIn via our website at <http://www.patriotplacements.org/> http://www.patriotplacements.org<http://patriotplacements.org/>



________________________________

**Comment by charlesabarnes** [comment]
Just taking a look again at this, I noticed that the index file name was changed.  I assume this was done to avoid file conflicts.  Instead of doing this, you should put all the files in a separate directory such as a directory for `/careers` so your files are not conflicting.

**Comment by charlesabarnes** [comment]
Instead of the root directory as there are multiple files that may be there with similar names.  Can you try adding it to the `careers` directory?

**Comment by PatriotPlacements** [comment]
Hi Charles:


I deleted our entire website and only put the code from GitHub up there and it was still blank.


I have also tried adding the careerportal folder to the root and calling the site, but a blank screen.  I have added it back.  It is live now for you to try.


http://patriotplacements.org/careerportal/index.html



[cid:31a1c523-5b57-4a78-b14b-b97584c637e0]






Thank you,
Carmelita Resh
Founder/CEO
Patriot Placements, Inc.

<http://www.patriotplacements.org/><http://www.patriotplacements.org>www.patriotplacements.org<http://www.patriotplacements.org/>

[1464298387064_PatriotPlacementsLogo]

Feel free to follow us on Facebook, Twitter or LinkedIn via our website at <http://www.patriotplacements.org/> http://www.patriotplacements.org<http://patriotplacements.org/>



________________________________

**Comment by charlesabarnes** [comment]
Hey Carmelita, 

It seems like you are still getting the MIME type error for the json file as it is returning 404.  That is the only thing that I am able to identify at the moment.  It may be best to discuss this with you directly instead of over GitHub.  I will be submitting this to our support team to follow up with you shortly.

**Comment by PatriotPlacements** [comment]
Hi Charles:


Great.  Thank you.  I am on EST time, but I work from 6:30am til 3pm in addition to the nonprofit.  Is it possible to schedule an evening support call?


Thank you,
Carmelita Resh
Founder/CEO
Patriot Placements, Inc.

<http://www.patriotplacements.org/><http://www.patriotplacements.org>www.patriotplacements.org<http://www.patriotplacements.org/>

[1464298387064_PatriotPlacementsLogo]

Feel free to follow us on Facebook, Twitter or LinkedIn via our website at <http://www.patriotplacements.org/> http://www.patriotplacements.org<http://patriotplacements.org/>



________________________________

**Comment by PatriotPlacements** [comment]
Hi Charles:


I figured out the issue with .json on GoDaddy Windows Plesk.   I had to go into:


My Plesk Admin > Web Server Settings > Mime Types


and add the following to the list


application/json .json

from this article:

https://stackoverflow.com/questions/9311747/godaddy-json-content-type-for-static-files

<https://stackoverflow.com/questions/9311747/godaddy-json-content-type-for-static-files>following what was in there already, I added:

font/woff2 .woff


Thank you for your help!


Thank you,
Carmelita Resh
Founder/CEO
Patriot Placements, Inc.

<http://www.patriotplacements.org/><http://www.patriotplacements.org>www.patriotplacements.org<http://www.patriotplacements.org/>

[1464298387064_PatriotPlacementsLogo]

Feel free to follow us on Facebook, Twitter or LinkedIn via our website at <http://www.patriotplacements.org/> http://www.patriotplacements.org<http://patriotplacements.org/>



________________________________

**Comment by charlesabarnes** [comment]
Thank you so much for sharing the solution with us! Also happy we were able to help b have a good rest of your week
