### ISSUE TITLE
Change language file in latest Bullhorn OSCP

### ISSUE THREAD

**Issue by BaboonBranding** [bullhorn/career-portal#292]
Hi,

I have installed the latest version of the Bullhorn plugin in my Wordpress website.
Unfortunately the latest version does not allow me to change the language packs because when opened in the editor there are no language files to be edited.

Currently the buttons are showing APPLY_NOW instead of Apply
This is the same for multiple buttons and pieces of text.

Can anyone help me change the language packs in the V3 of the Bullhorn OSCP?

**Comment by charlesabarnes** [comment]
Hello, 

It sounds like some files potentially didn't download correctly.  What locale are you attempting to use and what url is your career portal at?

**Comment by BaboonBranding** [comment]
I have updated my Bullhorn plugin within Wordpress.
I am using the US locale. The career portal is at https://www.tempforce.nl/vacatures/

**Comment by BaboonBranding** [comment]
<img width="1680" alt="Schermafbeelding 2019-11-06 om 19 06 49" src="https://user-images.githubusercontent.com/57456307/68324900-a03c7f80-00c8-11ea-89e4-8a05c13917ce.png">

This is what the US locale is showing in the plugin editor

**Comment by charlesabarnes** [comment]
It looks like the key for `APPLY_NOW` was updated to be `Solliciteren`.  Revert this change, and it should display properly.  

If you would like to add another language, add a file of your locale (looks to be `nl` so add `nl.json`), paste in the contents of one of the other json files, and replace the values to the right of each key.  

That will enable the proper translation method

**Comment by charlesabarnes** [comment]
Oh and you will need to add `nl` to the supported locales in the app.json file.

**Comment by BaboonBranding** [comment]
It is not only with the Apply now button, the problem is in every piece of default text

**Comment by BaboonBranding** [comment]
<img width="1680" alt="Schermafbeelding 2019-11-06 om 19 12 48" src="https://user-images.githubusercontent.com/57456307/68325346-7899e700-00c9-11ea-949b-10b3b1079cb0.png">
<img width="1680" alt="Schermafbeelding 2019-11-06 om 19 12 56" src="https://user-images.githubusercontent.com/57456307/68325347-79327d80-00c9-11ea-97f3-0ea30fe8cbbc.png">

**Comment by BaboonBranding** [comment]
I do not want to display the underscores, although Bullhorn doesn't let me change the language file.

**Comment by charlesabarnes** [comment]
Oh I see what is going on

**Comment by charlesabarnes** [comment]
Thanks for bringing this up, I am working to get this sorted ASAP

**Comment by charlesabarnes** [comment]
Can you try updating the plugin?  I released version 2.0.1 of the plugin to address this issue.  Apologies for the inconvenience. 

Please let me know if you have any questions

**Comment by BaboonBranding** [comment]
Hi Charles,

I updated the Bullhorn version, but the issue still persists...

**Comment by charlesabarnes** [comment]
I went through the test steps i preformed earlier and it seems to be working for me. can you try clearing your browser's cache? I know WordPress can be aggressive about caching.

**Comment by BaboonBranding** [comment]
Ah yea, seems to be working in Chrome! Safari not working yet although cleared cache. Need to check on that...

So now to change the language to NL I need to create a nl.json file?

**Comment by charlesabarnes** [comment]
Sweet! Thanks for making me aware of that issue. Also, correct, I suggest copying the English one and translating what you need in the nl.json file.

  Then, you will want to update the `supported locales` option to include `nl` on that list, and maybe set the default locale to be nl as well.

**Comment by BaboonBranding** [comment]
Hi Charles,

Sorry for my late response.

I added the correct language file and enabled NL in the app.json.
Unfortunately the language will not change to my language file... Could you see what is going wrong?
