### ISSUE TITLE
Bilingual Career Portal implementation with Bullhorn

### ISSUE THREAD

**Issue by Olivier-Recruscope** [bullhorn/career-portal#380]
Hello,

I would like to synchronize my website with Bullhorn for the career page. I am not a developer but I am the owner of the site and the company. Me and my programmer have tried to implement with Stu ( Bullhorn ) it but it does not work. There were some error codes while trying with Wordpress plugin, there was an HTTP 404 code.  

My site is on Wordpress and it is bilingual (English and French) So there are 2 pages for my career portal.

I will need help with the integration, how should I go about it and can someone help me?

Thanks,

Olivier

**Comment by pbearne** [comment]
Hi Olivier,

The OSCP might not the best solution for you. 
Where do you plan to manage the translations? 
Bullhorn doesn't support translated job descriptions. 

My WordPress plugin Matador Jobs may better solution for your needs as we can handle the Integration with WPML (your transition plugin).

Please reach out if you would like to see if we can help Paul@matadorjobs.com

Paul

**Comment by charlesabarnes** [comment]
Hello, 

With this career portal project you need to set up 2 separate portals as you will need 2 separate job listings for each job currently.  

What problems did you run into during setup?

**Comment by Olivier-Recruscope** [comment]
Hello Charles,

Cedric (my web developer) from Vertical System and I spent 45 minutes with Stu and we are unable to create the career page on Wordpress. It still doesn't work because it has errors.
Cedric would also like to see a website with wordpress that uses the Bullhorn API to see how it's done.
Stu recommended that we create another website for the career page which is still a big project and I don't want to get into it for now...
All I want is the CVs of candidates who apply on my website to be added directly to my ATS Bullhorn.
You may know you know clients who have bilingual sites.
Cedric, doesn’t understand why tese APIs are not bilingual.

I am not a developer and I just want to have my portal carrer working with Bullhorn.

Let me know if you can help.

Thanks for your time.

Best regards,




Olivier Parent, CRHA
[Une image contenant assis, signe, dessin, alimentation  Description générée automatiquement]
Recherche de cadres
***@***.******@***.***>
Cell : 438-870-7075
www.recruscope.com<http://www.recruscope.com/>


AVIS DE CONFIDENTIALITÉ     Le contenu de ce message ainsi que du ou des fichiers qui y sont joints est strictement confidentiel et destiné exclusivement à son ou sa destinataire. Si vous n’êtes pas cette personne, nous attirons votre attention sur le fait qu’il est strictement interdit de copier, de faire suivre ou d’utiliser les informations contenues dans ce courriel. Si vous l’avez reçu par erreur, nous vous remercions de nous le faire savoir.

CONFIDENTIALITY NOTICE     This message and any attachments are confidential and may contain privileged information intended only for the identified recipient. Anyone else must not copy, use, store or disseminate the message, attachments or information without permission.



De : Charles Barnes ***@***.***>
Envoyé : 22 avril 2021 18:41
À : bullhorn/career-portal ***@***.***>
Cc : Olivier Parent ***@***.***>; Author ***@***.***>
Objet : Re: [bullhorn/career-portal] Bilingual Career Portal implementation with Bullhorn (#380)


Hello,

With this career portal project you need to set up 2 separate portals as you will need 2 separate job listings for each job currently.

What problems did you run into during setup?

**Comment by charlesabarnes** [comment]
Hello,  I do not have any example wordpress environments to provide right now, though the API is the same regardless.  The Bullhorn wordpress plugin is an iframed version of the career portal that is found in this Github repository.  You can find an example of the portal [here ](http://bh-career-portal-example.herokuapp.com/ ).  Configuration requires only 2 parameters: `swimlane` and `corp token` which are set in the app.json file (Or under the plugin configuration in wp-admin).    If the error you are receiving is provided, I will be able to provide you with more pointed guidance.   

I do want to add that most APIs powered by user submitted data are not directly bilingual, they either access 2 separate sets of data (which I am proposing here) or go through a translation middleware.   Both have their pros and cons.

**Comment by Olivier-Recruscope** [comment]
Hello Charles,

the integration of my career page is still not working.

Here is the test page that my developer made : https://recruscope.com/test/

My developer went through the steps one by one and it still doesn't work.

My developer recommends that I give you temporary access to my website to repair your API which, according to him, is not working. Let my know your email and we will provide you a temporary user to signin in my website.

Please help me make this work,

Regards,


Olivier Parent, CRHA
[Une image contenant assis, signe, dessin, alimentation  Description générée automatiquement]
Recherche de cadres
***@***.******@***.***>
Cell : 438-870-7075
www.recruscope.com<http://www.recruscope.com/>


AVIS DE CONFIDENTIALITÉ     Le contenu de ce message ainsi que du ou des fichiers qui y sont joints est strictement confidentiel et destiné exclusivement à son ou sa destinataire. Si vous n’êtes pas cette personne, nous attirons votre attention sur le fait qu’il est strictement interdit de copier, de faire suivre ou d’utiliser les informations contenues dans ce courriel. Si vous l’avez reçu par erreur, nous vous remercions de nous le faire savoir.

CONFIDENTIALITY NOTICE     This message and any attachments are confidential and may contain privileged information intended only for the identified recipient. Anyone else must not copy, use, store or disseminate the message, attachments or information without permission.



De : Charles Barnes ***@***.***>
Envoyé : 27 avril 2021 18:06
À : bullhorn/career-portal ***@***.***>
Cc : Olivier Parent ***@***.***>; Author ***@***.***>
Objet : Re: [bullhorn/career-portal] Bilingual Career Portal implementation with Bullhorn (#380)


Hello, I do not have any example wordpress environments to provide right now, though the API is the same regardless. The Bullhorn wordpress plugin is an iframed version of the career portal that is found in this Github repository. You can find an example of the portal here <http://bh-career-portal-example.herokuapp.com/> . Configuration requires only 2 parameters: swimlane and corp token which are set in the app.json file (Or under the plugin configuration in wp-admin). If the error you are receiving is provided, I will be able to provide you with more pointed guidance.

I do want to add that most APIs powered by user submitted data are not directly bilingual, they either access 2 separate sets of data (which I am proposing here) or go through a translation middleware. Both have their pros and cons.

**Comment by charlesabarnes** [comment]
Hey, thank you for providing a link.   

It looks like the API is disabled on our end.  Bullhorn Support can enable this.   Everything is correct on your end.

I know you have already been working with Support so I am reaching out internally on my end to remedy this for you.  Apologies for diffulties

**Comment by Olivier-Recruscope** [comment]
Hello Charles,

Yes, this is what my développer told Stu when we dit it with him last time.

Could we do it bilingual or only french or english for my website ?


My developper recommand you to create  an API Wordpress bilingual unstead of unlingual.

Thanks,



Olivier Parent, CRHA
[Une image contenant assis, signe, dessin, alimentation  Description générée automatiquement]
Recherche de cadres
***@***.******@***.***>
Cell : 438-870-7075
www.recruscope.com<http://www.recruscope.com/>


AVIS DE CONFIDENTIALITÉ     Le contenu de ce message ainsi que du ou des fichiers qui y sont joints est strictement confidentiel et destiné exclusivement à son ou sa destinataire. Si vous n’êtes pas cette personne, nous attirons votre attention sur le fait qu’il est strictement interdit de copier, de faire suivre ou d’utiliser les informations contenues dans ce courriel. Si vous l’avez reçu par erreur, nous vous remercions de nous le faire savoir.

CONFIDENTIALITY NOTICE     This message and any attachments are confidential and may contain privileged information intended only for the identified recipient. Anyone else must not copy, use, store or disseminate the message, attachments or information without permission.



De : Charles Barnes ***@***.***>
Envoyé : 4 mai 2021 14:15
À : bullhorn/career-portal ***@***.***>
Cc : Olivier Parent ***@***.***>; Author ***@***.***>
Objet : Re: [bullhorn/career-portal] Bilingual Career Portal implementation with Bullhorn (#380)


Hey, thank you for providing a link.

It looks like the API is disabled on our end. Bullhorn Support can enable this. Everything is correct on your end.

I know you have already been working with Support so I am reaching out internally on my end to remedy this for you. Apologies for diffulties

**Comment by EricNLecuyer** [comment]
Salut Olivier,

Just in case it is useful to your implementation, here is a portal I implemented a few years ago : 
Portal (standalone app): http://jobs.lindispensable.com/#/jobs
WP Site: https://lindispensable.com/fr/trouvez-votre-futur-poste/

Basically, the positions are showcased on the WP site in the current browsing language (i.e. only FR positions on the FR page, opposite in EN) with a simple hyperlink to their page in the portal. In the portal, all the positions in both languages are shown, but we added a language filter in case users wanted to narrow down their results. This method has its drawback, but it was our best option at the time. 

I'm not maintaining this site anymore though and haven't followed the development of the Bullhorn frontend app for quite some time so I don't know if new features for translations have been added since. Hope this still helps!

Bonne implantation,
Eric

**Comment by pbearne** [comment]
Hi All

We have a number of clients with multi-lingual sites
There 2 methods that can be used
1. Use a custom field in Bullhorn to store the translated desicptions and translate in the WP the tax strings etc. and then swap on the fly to the correct lang.
2. Import the primary lang as normal and use a WordPress translation Plugin to handle /manage the additional languages as needed
  
which method mainly depends on who is doing the translation work.

I hope this helps
Paul

**Comment by Olivier-Recruscope** [comment]
Hello Charles,

Ok, do you went the you will be able to fix the API ? It is still not working.

Thanks,


Olivier Parent, CRHA
[Une image contenant assis, signe, dessin, alimentation  Description générée automatiquement]
Recherche de cadres
***@***.******@***.***>
Cell : 438-870-7075
www.recruscope.com<http://www.recruscope.com/>


AVIS DE CONFIDENTIALITÉ     Le contenu de ce message ainsi que du ou des fichiers qui y sont joints est strictement confidentiel et destiné exclusivement à son ou sa destinataire. Si vous n’êtes pas cette personne, nous attirons votre attention sur le fait qu’il est strictement interdit de copier, de faire suivre ou d’utiliser les informations contenues dans ce courriel. Si vous l’avez reçu par erreur, nous vous remercions de nous le faire savoir.

CONFIDENTIALITY NOTICE     This message and any attachments are confidential and may contain privileged information intended only for the identified recipient. Anyone else must not copy, use, store or disseminate the message, attachments or information without permission.



De : Charles Barnes ***@***.***>
Envoyé : 4 mai 2021 14:15
À : bullhorn/career-portal ***@***.***>
Cc : Olivier Parent ***@***.***>; Author ***@***.***>
Objet : Re: [bullhorn/career-portal] Bilingual Career Portal implementation with Bullhorn (#380)


Hey, thank you for providing a link.

It looks like the API is disabled on our end. Bullhorn Support can enable this. Everything is correct on your end.

I know you have already been working with Support so I am reaching out internally on my end to remedy this for you. Apologies for diffulties
